EVT_PRINT_ERROR = 0
EVT_CONNECTION_ERROR = 1

SERVER_RESPONSE_UPLOAD_FAILURE = b'0'
SERVER_RESPONSE_UPLOAD_SUCCESS = b'1'
SERVER_RESPONSE_QUERY_FAILURE = b'2'
SERVER_RESPONSE_QUERY_SUCCESS = b'3'

REQUEST_TYPE_UPLOAD = b'0'
REQUEST_TYPE_QUERY = b'1'

COLLECTION_SAMPLE = u'kwic_collection'
DOCUMENT_QUERY_URLS = u'kwic_query_document'
ARG_KWIC_KEYWORD_DATA = u'kwicKeywordData'
ARG_URL_ORIGINAL_KEYWORDS = u'urlOriginalKeywords'
ARG_URL = u'url'
ARG_NOISE_WORDS = u'noiseWords'
ARG_KEYWORDS = u'keywords'