EVT_PRINT_ERROR = 0
EVT_CONNECTION_ERROR = 1

SERVER_RESPONSE_FAILURE = '0'
SERVER_RESPONSE_SUCCESS = '1'

REQUEST_TYPE_UPLOAD = '0'
REQUEST_TYPE_GET = '1'

COLLECTION_SAMPLE = u'kwic_collection'
DOCUMENT_QUERY_URLS = u'kwic_query_document'
ARG_KWIC_KEYWORD_DATA = u'kwicKeywordData'
ARG_URL_ORIGINAL_KEYWORDS = u'urlOriginalKeywords'
ARG_URL = u'url'
ARG_KEYWORDS = u'keywords'